name: Flux Helm Preview
description: Render and diff Flux GitOps kustomizations and helm releases to preview PR changes
author: Tobias Habermann
inputs:
  helm:
    description: 'Render HelmRelease resources'
    required: false
    default: "false"
  kustomizations:
    description: 'List of kustomizations to render (newline separated)'
    required: true
  repo-a:
    description: 'Path to repository A'
    required: true
  repo-b:
    description: 'Path to repository B'
    required: true
  write-markdown:
    description: 'Write markdown diff comment to a file'
    required: false
    default: ""
  markdown-template:
    description: 'Template for markdown output'
    required: false
    default: |-
      # Flux Helm Preview
      ```diff
      {{ .Diff }}
      ```
  filter:
    description: KIO filters to apply to rendered YAML
    required: false
    default: ""
outputs:
  diff:
    description: Diff in Markdown format
    value: ${{ steps.fhp.outputs.diff }}
runs:
  using: 'composite'
  steps:
    - uses: actions/setup-go@v3
      with:
        go-version: '>=1.18.0'
    - name: Download Go modules
      run: go mod download
      working-directory: ${{ github.action_path }}
      shell: bash
    - name: Flux Helm Preview
      id: fhp
      run: go run main.go
      working-directory: ${{ github.action_path }}/cmd/action
      shell: bash