name: Binary Release
on:
  workflow_dispatch:
    inputs:
      tag:
        required: true
        description: Tag to release
      target_branch:
        required: false
        description: Target branch
        default: main
  workflow_call:
    secrets:
      APP_ID:
        required: true
      APP_INSTALLATION_ID:
        required: true
      PRIVATE_KEY:
        required: true
    inputs:
      tag:
        type: string
        required: true
        description: Tag to release
      target_branch:
        type: string
        required: false
        description: Target branch
        default: main
jobs:
  binary-release:
    name: Binary release
    runs-on: ubuntu-latest
    env:
      GO111MODULE: on
      CGO_ENABLED: 0
      GOOS: linux
      GOARCH: amd64
    steps:
      - name: Generate token
        id: generate_token
        uses: tibdex/github-app-token@v1
        with:
          app_id: ${{ secrets.APP_ID }}
          private_key: ${{ secrets.PRIVATE_KEY }}
          installation_id: ${{ secrets.APP_INSTALLATION_ID }}
      - uses: actions/checkout@master
      - uses: actions/setup-go@v3
        with:
          go-version: 1.18.x
          cache: true
          cache-dependency-path: go.sum
      - run:  go build -ldflags "-s -w -extldflags '-static'" -o build/fhp ./cmd/action && strip build/fhp
      - name: Run UPX
        uses: crazy-max/ghaction-upx@v2
        with:
          version: latest
          files: |
            ./build/fhp
      - run: cp cmd/action/{action.yml,invoke_binary.js} build/
      - run: actions/setup-git@v2
        with:
          user_name: fhp-release-bot
          user_email: fhp-release-bot@bot
      - run: |-
          git clone https://x-access-token:${{ secrets.GITHUB_TOKEN }}@github.com/tobiash/flux-helm-preview-action.git release
          cd release
          if ! git rev-parse --verify ${{ inputs.target_branch }} >/dev/null 2>&1; then
            git checkout -b ${{ inputs.target_branch }}
          else
            git checkout ${{ inputs.target_branch }}
          fi
          git checkout -b ${{ inputs.target_branch }}
          cp -r ../build/* release/
          git add .
          git commit -m "Build release ${{ inputs.tag }}"
          git tag "${{ inputs.tag }}"
          git push origin HEAD:${{ inputs.target_branch }} --tags 
